version: '3.1'

services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: coffee-shop
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
  api:
    build:
      dockerfile: ./Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - 8000:3000
    volumes:
      - uploads:/app/public/uploads
    depends_on:
      - db

volumes:
  db:
  uploads:
